apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/common/istio-1-9-0/istio-namespace/base
- github.com/kubeflow/manifests/common/istio-1-9-0/istio-crds/base
- github.com/kubeflow/manifests/common/istio-1-9-0/istio-install/base
- github.com/kubeflow/manifests/common/istio-1-9-0/cluster-local-gateway/base
- github.com/kubeflow/manifests/common/istio/istio/base
- github.com/kubeflow/manifests/common/istio/oidc-authservice/base
# for HTTPS, create a certificate with name `istio-ingressgateway-certs`
# in the `istio-system` namespace, comment out the previous line and
# uncomment the following line
# - github.com/kubeflow/manifests/common/istio/istio/overlays/https-gateway/

patchesStrategicMerge:
- gateway-service.yaml

images:
- name: docker.io/istio/proxyv2
  newName: docker.io/istio/proxyv2
  newTag: 1.9.1
- name: docker.io/istio/pilot
  newName: docker.io/istio/pilot
  newTag: 1.9.1
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: gcr.io/arrikto/kubeflow/oidc-authservice
  newTag: 28c59ef
