apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/common/istio-1-9-0/istio-namespace/base
- github.com/kubeflow/manifests/common/istio-1-9-0/istio-crds/base
- github.com/kubeflow/manifests/common/istio-1-9-0/istio-install/base
- github.com/kubeflow/manifests/common/istio-1-9-0/cluster-local-gateway/base
- github.com/kubeflow/manifests/common/istio-1-9-0/kubeflow-istio-resources/base

patchesStrategicMerge:
- gateway-service.yaml
- sidecar-configmap-patch.yaml
# for HTTPS, create a certificate with name `istio-ingressgateway-certs`
# in the `istio-system` namespace and uncomment the following line
- https-gateway.yaml

images:
- name: docker.io/istio/proxyv2
  newName: docker.io/istio/proxyv2
  newTag: 1.9.2
- name: docker.io/istio/pilot
  newName: docker.io/istio/pilot
  newTag: 1.9.2
